export default [
  { name: "John Doe", tutors: "Maria Rodriguez", state: "Regular" },
  { name: "Jane Smith", tutors: "David Garcia", state: "Regular" },
  { name: "Michael Johnson", tutors: "Laura Martinez", state: "Regular" },
  { name: "Emily Brown", tutors: "Carlos Perez", state: "Regular" },
  { name: "Daniel Wilson", tutors: "Ana Lopez", state: "Regular" },
  { name: "Sarah Taylor", tutors: "Miguel Sanchez", state: "Regular" },
  { name: "Christopher Martin", tutors: "Sofia Ramirez", state: "Regular" },
  { name: "Amanda Thompson", tutors: "Javier Hernandez", state: "Regular" },
  { name: "David Anderson", tutors: "Paula Gonzalez", state: "Regular" },
  { name: "Jessica White", tutors: "Diego Lopez", state: "Regular" },
  { name: "Matthew Martinez", tutors: "Patricia Fernandez", state: "Regular" },
  { name: "Ashley Harris", tutors: "Alejandro Ruiz", state: "Regular" },
  { name: "James Clark", tutors: "Carmen Torres", state: "Regular" },
  { name: "Elizabeth King", tutors: "Pablo Morales", state: "Regular" },
  { name: "Ryan Lee", tutors: "Rosa Diaz", state: "Regular" },
  { name: "Olivia Lewis", tutors: "Roberto Ortiz", state: "Regular" },
  { name: "Joshua Walker", tutors: "Elena Castro", state: "Regular" },
  { name: "Sophia Green", tutors: "Manuel Navarro", state: "Regular" },
  { name: "Andrew Baker", tutors: "Isabel Soto", state: "Regular" },
];
